Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,10 +11,17 @@ jobs:
       - name: Get secret from source repo
         id: get-secret
         run: |
-          SECRET_VALUE=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
+          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/LexionN/devops-diplom/actions/secrets/TF_VAR_FOLDER_ID)
-          echo "SECRET_VALUE=$(echo $SECRET_VALUE | jq -r .value)" >> $GITHUB_ENV
+
+          if [[ $(echo "$RESPONSE" | jq -r .message) == "Not Found" ]]; then
+            echo "Secret not found or insufficient permissions."
+            exit 1
+          fi
+
+          SECRET_VALUE=$(echo "$RESPONSE" | jq -r .value)
+          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV
 
       - name: Use the secret
         run: |
